CREATE TABLE holidays(id INTEGER NOT NULL PRIMARY KEY, Date TEXT NOT NULL, HolidayName TEXT NOT NULL, Information TEXT NOT NULL, MoreInformation TEXT NOT NULL, Jurisdiction TEXT NOT NULL);

INSERT INTO holidays(Date,HolidayName,Information,MoreInformation,Jurisdiction,id) VALUES 
("20250101","New Year's Day"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",1),
("20250127","Australia Day"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",2),
("20250310","Canberra Day"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",3),
("20250418","Good Friday"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",4),
("20250419","Easter Saturday - the day after Good Friday"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",5),
("20250420","Easter Sunday"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",6),
("20250421","Easter Monday"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",7),
("20250425","ANZAC Day"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",8),
("20250602","Reconciliation Day"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",9),
("20250609","King's Birthday"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",10),
("20251006","Labour Day"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",11),
("20251225","Christmas Day"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",12),
("20251226","Boxing Day"," ","https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-savings","act",13),
("20250101","New Year's Day"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",14),
("20250127","Australia Day"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",15),
("20250418","Good Friday"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",16),
("20250419","Easter Saturday"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",17),
("20250420","Easter Sunday"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",18),
("20250421","Easter Monday"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",19),
("20250425","Anzac Day"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",20),
("20250609","King's Birthday"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",21),
("20250804","Bank Holiday","Applies to banks and certain financial institutions, see the Retail Trading Act 2008.","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",22),
("20251006","Labour Day"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",23),
("20251225","Christmas Day"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",24),
("20251226","Boxing Day"," ","https://www.nsw.gov.au/about-nsw/public-holidays","nsw",25),
("20250101","New Year's Day"," ","https://www.nt.gov.au/nt-public-holidays","nt",26),
("20250127","Australia Day"," ","https://www.nt.gov.au/nt-public-holidays","nt",27),
("20250418","Good Friday"," ","https://www.nt.gov.au/nt-public-holidays","nt",28),
("20250419","Easter Saturday"," ","https://www.nt.gov.au/nt-public-holidays","nt",29),
("20250420","Easter Sunday"," ","https://www.nt.gov.au/nt-public-holidays","nt",30),
("20250421","Easter Monday"," ","https://www.nt.gov.au/nt-public-holidays","nt",31),
("20250425","Anzac Day"," ","https://www.nt.gov.au/nt-public-holidays","nt",32),
("20250505","May Day"," ","https://www.nt.gov.au/nt-public-holidays","nt",33),
("20250609","King's Birthday"," ","https://www.nt.gov.au/nt-public-holidays","nt",34),
("20250704","Alice Springs Show Day","Regional holiday - to find out which show day applies to your area, check the map of NT show day regions.","https://www.nt.gov.au/nt-public-holidays","nt",35),
("20250711","Tennant Creek Show Day","Regional holiday - to find out which show day applies to your area, check the map of NT show day regions.","https://www.nt.gov.au/nt-public-holidays","nt",36),
("20250718","Katherine Show Day","Regional holiday - to find out which show day applies to your area, check the map of NT show day regions.","https://www.nt.gov.au/nt-public-holidays","nt",37),
("20250725","Darwin Show Day","Regional holiday - to find out which show day applies to your area, check the map of NT show day regions.","https://www.nt.gov.au/nt-public-holidays","nt",38),
("20250804","Picnic Day"," ","https://www.nt.gov.au/nt-public-holidays","nt",39),
("20251224","Christmas Eve - part day holiday","Part day holiday - from 7pm to midnight only.","https://www.nt.gov.au/nt-public-holidays","nt",40),
("20251225","Christmas Day"," ","https://www.nt.gov.au/nt-public-holidays","nt",41),
("20251226","Boxing Day"," ","https://www.nt.gov.au/nt-public-holidays","nt",42),
("20251231","New Year's Eve - part day holiday","Part day holiday - from 7pm to midnight only.","https://www.nt.gov.au/nt-public-holidays","nt",43),
("20250101","New Year's Day"," ","https://www.qld.gov.au/recreation/travel/holidays/public","qld",44),
("20250127","Australia Day","Australia Day public holiday is to be observed on the 26 January or, if 26 January is a Saturday or Sunday, it shall be observed the following Monday.","https://www.qld.gov.au/recreation/travel/holidays/public","qld",45),
("20250418","Good Friday"," ","https://www.qld.gov.au/recreation/travel/holidays/public","qld",46),
("20250419","The day after Good Friday"," ","https://www.qld.gov.au/recreation/travel/holidays/public","qld",47),
("20250420","Easter Sunday","Easter Sunday is appointed as a public holiday. These arrangements have been in place since 2017 following amendments to the Holidays Act 1983 (passed by Parliament on 1 December 2016).","https://www.qld.gov.au/recreation/travel/holidays/public","qld",48),
("20250421","Easter Monday"," ","https://www.qld.gov.au/recreation/travel/holidays/public","qld",49),
("20250425","Anzac Day"," ","https://www.qld.gov.au/recreation/travel/holidays/public","qld",50),
("20250505","Labour Day","Labour Day public holiday is to be observed on the first Monday in May and the Birthday of the Sovereign (King's Birthday) public holiday is to be observed on the first Monday in October. These arrangements have been in place since 2016 following amendments to the Holidays Act 1983 (passed by Parliament on 13 October 2015).","https://www.qld.gov.au/recreation/travel/holidays/public","qld",51),
("20250813","Royal Queensland Show (Brisbane area only)","The Royal National Agricultural (RNA) Show Day (Brisbane only) is held on the Wednesday during the RNA Show period. The RNA Show commences on the first Friday in August, unless the first Friday is prior to 5 August, then it commences on the second Friday of August.","https://www.qld.gov.au/recreation/travel/holidays/public","qld",52),
("20251006","King's Birthday","Labour Day public holiday is to be observed on the first Monday in May and the Birthday of the Sovereign (King's Birthday) public holiday is to be observed on the first Monday in October. These arrangements have been in place since 2016 following amendments to the Holidays Act 1983 (passed by Parliament on 13 October 2015).","https://www.qld.gov.au/recreation/travel/holidays/public","qld",53),
("20251224","Christmas Eve (24 December) 6pm - midnight","From 2019, the Holidays Act 1983 provides for a part-day public holiday from 6pm to midnight on Christmas Eve (24 December).","https://www.qld.gov.au/recreation/travel/holidays/public","qld",54),
("20251225","Christmas Day"," ","https://www.qld.gov.au/recreation/travel/holidays/public","qld",55),
("20251226","Boxing Day"," ","https://www.qld.gov.au/recreation/travel/holidays/public","qld",56),
("20250101","New Years Day"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",57),
("20250127","Australia Day public holiday"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",58),
("20250310","Adelaide Cup Day"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",59),
("20250418","Good Friday"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",60),
("20250419","Easter Saturday"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",61),
("20250420","Easter Sunday"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",62),
("20250421","Easter Monday"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",63),
("20250425","ANZAC Day"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",64),
("20250609","Kings Birthday"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",65),
("20251006","Labour Day"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",66),
("20251224","Christmas Eve: 7pm to midnight"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",67),
("20251225","Christmas Day"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",68),
("20251226","Proclamation Day holiday and Boxing Day"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",69),
("20251231","New Years Eve: 7pm to midnight"," ","https://www.safework.sa.gov.au/resources/public-holidays","sa",70),
("20250101","New Year's Day"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",71),
("20250127","Australia Day"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",72),
("20250310","Eight Hours Day"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",73),
("20250418","Good Friday"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",74),
("20250421","Easter Monday"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",75),
("20250422","Easter Tuesday - generally Tasmanian Public Service only"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",76),
("20250425","ANZAC Day"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",77),
("20250609","King's Birthday"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",78),
("20251225","Christmas Day"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",79),
("20251226","Boxing Day"," ","https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays","tas",80),
("20250101","New Year's Day"," ","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",81),
("20250127","Australia Day","As Australia Day falls on a Sunday, the public holiday is on the following Monday.","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",82),
("20250310","Labour Day"," ","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",83),
("20250418","Good Friday","ANZAC Day, Good Friday and Christmas Day are restricted trading days.","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",84),
("20250419","Saturday before Easter Sunday"," ","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",85),
("20250420","Easter Sunday"," ","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",86),
("20250421","Easter Monday"," ","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",87),
("20250425","ANZAC Day","ANZAC Day, Good Friday and Christmas Day are restricted trading days.","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",88),
("20250609","King's Birthday"," ","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",89),
(" ","Friday before the AFL Grand Final","Friday before AFL Grand Final typically falls on the last Friday in September. The Business Victoria website will be updated with the exact date upon release of the 2025 AFL schedule.","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",90),
("20251104","Melbourne Cup","Melbourne Cup Day is a public holiday across all of Victoria unless alternate local holiday has been arranged by a non-metro council.","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",91),
("20251225","Christmas Day","ANZAC Day, Good Friday and Christmas Day are restricted trading days.","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",92),
("20251226","Boxing Day"," ","https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2025","vic",93),
("20250101","New Year's Day"," ","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",94),
("20250127","Australia Day"," ","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",95),
("20250303","Labour Day"," ","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",96),
("20250418","Good Friday"," ","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",97),
("20250420","Easter Sunday","Easter Sunday was established as a public holiday in Western Australia in February 2022. Visit the Easter Sunday public holiday page for more information.","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",98),
("20250421","Easter Monday"," ","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",99),
("20250425","Anzac Day"," ","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",100),
("20250602","Western Australia Day"," ","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",101),
("20250929","King's Birthday","This public holiday now known as the King's Birthday, was previously known as the Queen’s Birthday. Some regional areas in WA hold this public holiday on a different date - the 2024 dates are on the Regional WA public holiday dates page.","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",102),
("20251225","Christmas Day"," ","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",103),
("20251226","Boxing Day"," ","https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia","wa",104);